// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef PROTOBUF_INCLUDED_messages_2eproto
#define PROTOBUF_INCLUDED_messages_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_messages_2eproto 

namespace protobuf_messages_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_messages_2eproto
namespace com {
namespace my {
namespace jni {
namespace dlib {
namespace data {
class Face;
class FaceDefaultTypeInternal;
extern FaceDefaultTypeInternal _Face_default_instance_;
class FaceList;
class FaceListDefaultTypeInternal;
extern FaceListDefaultTypeInternal _FaceList_default_instance_;
class Landmark;
class LandmarkDefaultTypeInternal;
extern LandmarkDefaultTypeInternal _Landmark_default_instance_;
class LandmarkList;
class LandmarkListDefaultTypeInternal;
extern LandmarkListDefaultTypeInternal _LandmarkList_default_instance_;
class RectF;
class RectFDefaultTypeInternal;
extern RectFDefaultTypeInternal _RectF_default_instance_;
class RectFList;
class RectFListDefaultTypeInternal;
extern RectFListDefaultTypeInternal _RectFList_default_instance_;
}  // namespace data
}  // namespace dlib
}  // namespace jni
}  // namespace my
}  // namespace com
namespace google {
namespace protobuf {
template<> ::com::my::jni::dlib::data::Face* Arena::CreateMaybeMessage<::com::my::jni::dlib::data::Face>(Arena*);
template<> ::com::my::jni::dlib::data::FaceList* Arena::CreateMaybeMessage<::com::my::jni::dlib::data::FaceList>(Arena*);
template<> ::com::my::jni::dlib::data::Landmark* Arena::CreateMaybeMessage<::com::my::jni::dlib::data::Landmark>(Arena*);
template<> ::com::my::jni::dlib::data::LandmarkList* Arena::CreateMaybeMessage<::com::my::jni::dlib::data::LandmarkList>(Arena*);
template<> ::com::my::jni::dlib::data::RectF* Arena::CreateMaybeMessage<::com::my::jni::dlib::data::RectF>(Arena*);
template<> ::com::my::jni::dlib::data::RectFList* Arena::CreateMaybeMessage<::com::my::jni::dlib::data::RectFList>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace com {
namespace my {
namespace jni {
namespace dlib {
namespace data {

// ===================================================================

class Landmark : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:com.my.jni.dlib.data.Landmark) */ {
 public:
  Landmark();
  virtual ~Landmark();

  Landmark(const Landmark& from);

  inline Landmark& operator=(const Landmark& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Landmark(Landmark&& from) noexcept
    : Landmark() {
    *this = ::std::move(from);
  }

  inline Landmark& operator=(Landmark&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const Landmark& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Landmark* internal_default_instance() {
    return reinterpret_cast<const Landmark*>(
               &_Landmark_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Landmark* other);
  friend void swap(Landmark& a, Landmark& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Landmark* New() const final {
    return CreateMaybeMessage<Landmark>(NULL);
  }

  Landmark* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Landmark>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const Landmark& from);
  void MergeFrom(const Landmark& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Landmark* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // @@protoc_insertion_point(class_scope:com.my.jni.dlib.data.Landmark)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  float x_;
  float y_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LandmarkList : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:com.my.jni.dlib.data.LandmarkList) */ {
 public:
  LandmarkList();
  virtual ~LandmarkList();

  LandmarkList(const LandmarkList& from);

  inline LandmarkList& operator=(const LandmarkList& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LandmarkList(LandmarkList&& from) noexcept
    : LandmarkList() {
    *this = ::std::move(from);
  }

  inline LandmarkList& operator=(LandmarkList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const LandmarkList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LandmarkList* internal_default_instance() {
    return reinterpret_cast<const LandmarkList*>(
               &_LandmarkList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(LandmarkList* other);
  friend void swap(LandmarkList& a, LandmarkList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LandmarkList* New() const final {
    return CreateMaybeMessage<LandmarkList>(NULL);
  }

  LandmarkList* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LandmarkList>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const LandmarkList& from);
  void MergeFrom(const LandmarkList& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LandmarkList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.my.jni.dlib.data.Landmark landmarks = 1;
  int landmarks_size() const;
  void clear_landmarks();
  static const int kLandmarksFieldNumber = 1;
  ::com::my::jni::dlib::data::Landmark* mutable_landmarks(int index);
  ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Landmark >*
      mutable_landmarks();
  const ::com::my::jni::dlib::data::Landmark& landmarks(int index) const;
  ::com::my::jni::dlib::data::Landmark* add_landmarks();
  const ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Landmark >&
      landmarks() const;

  // @@protoc_insertion_point(class_scope:com.my.jni.dlib.data.LandmarkList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Landmark > landmarks_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RectF : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:com.my.jni.dlib.data.RectF) */ {
 public:
  RectF();
  virtual ~RectF();

  RectF(const RectF& from);

  inline RectF& operator=(const RectF& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RectF(RectF&& from) noexcept
    : RectF() {
    *this = ::std::move(from);
  }

  inline RectF& operator=(RectF&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const RectF& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RectF* internal_default_instance() {
    return reinterpret_cast<const RectF*>(
               &_RectF_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(RectF* other);
  friend void swap(RectF& a, RectF& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RectF* New() const final {
    return CreateMaybeMessage<RectF>(NULL);
  }

  RectF* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RectF>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const RectF& from);
  void MergeFrom(const RectF& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RectF* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float left = 1;
  void clear_left();
  static const int kLeftFieldNumber = 1;
  float left() const;
  void set_left(float value);

  // float top = 2;
  void clear_top();
  static const int kTopFieldNumber = 2;
  float top() const;
  void set_top(float value);

  // float right = 3;
  void clear_right();
  static const int kRightFieldNumber = 3;
  float right() const;
  void set_right(float value);

  // float bottom = 4;
  void clear_bottom();
  static const int kBottomFieldNumber = 4;
  float bottom() const;
  void set_bottom(float value);

  // @@protoc_insertion_point(class_scope:com.my.jni.dlib.data.RectF)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  float left_;
  float top_;
  float right_;
  float bottom_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RectFList : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:com.my.jni.dlib.data.RectFList) */ {
 public:
  RectFList();
  virtual ~RectFList();

  RectFList(const RectFList& from);

  inline RectFList& operator=(const RectFList& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RectFList(RectFList&& from) noexcept
    : RectFList() {
    *this = ::std::move(from);
  }

  inline RectFList& operator=(RectFList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const RectFList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RectFList* internal_default_instance() {
    return reinterpret_cast<const RectFList*>(
               &_RectFList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(RectFList* other);
  friend void swap(RectFList& a, RectFList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RectFList* New() const final {
    return CreateMaybeMessage<RectFList>(NULL);
  }

  RectFList* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RectFList>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const RectFList& from);
  void MergeFrom(const RectFList& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RectFList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.my.jni.dlib.data.RectF rects = 1;
  int rects_size() const;
  void clear_rects();
  static const int kRectsFieldNumber = 1;
  ::com::my::jni::dlib::data::RectF* mutable_rects(int index);
  ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::RectF >*
      mutable_rects();
  const ::com::my::jni::dlib::data::RectF& rects(int index) const;
  ::com::my::jni::dlib::data::RectF* add_rects();
  const ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::RectF >&
      rects() const;

  // @@protoc_insertion_point(class_scope:com.my.jni.dlib.data.RectFList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::RectF > rects_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Face : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:com.my.jni.dlib.data.Face) */ {
 public:
  Face();
  virtual ~Face();

  Face(const Face& from);

  inline Face& operator=(const Face& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Face(Face&& from) noexcept
    : Face() {
    *this = ::std::move(from);
  }

  inline Face& operator=(Face&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const Face& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Face* internal_default_instance() {
    return reinterpret_cast<const Face*>(
               &_Face_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Face* other);
  friend void swap(Face& a, Face& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Face* New() const final {
    return CreateMaybeMessage<Face>(NULL);
  }

  Face* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Face>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const Face& from);
  void MergeFrom(const Face& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Face* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.my.jni.dlib.data.Landmark landmarks = 2;
  int landmarks_size() const;
  void clear_landmarks();
  static const int kLandmarksFieldNumber = 2;
  ::com::my::jni::dlib::data::Landmark* mutable_landmarks(int index);
  ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Landmark >*
      mutable_landmarks();
  const ::com::my::jni::dlib::data::Landmark& landmarks(int index) const;
  ::com::my::jni::dlib::data::Landmark* add_landmarks();
  const ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Landmark >&
      landmarks() const;

  // .com.my.jni.dlib.data.RectF bound = 1;
  bool has_bound() const;
  void clear_bound();
  static const int kBoundFieldNumber = 1;
  private:
  const ::com::my::jni::dlib::data::RectF& _internal_bound() const;
  public:
  const ::com::my::jni::dlib::data::RectF& bound() const;
  ::com::my::jni::dlib::data::RectF* release_bound();
  ::com::my::jni::dlib::data::RectF* mutable_bound();
  void set_allocated_bound(::com::my::jni::dlib::data::RectF* bound);

  // @@protoc_insertion_point(class_scope:com.my.jni.dlib.data.Face)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Landmark > landmarks_;
  ::com::my::jni::dlib::data::RectF* bound_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FaceList : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:com.my.jni.dlib.data.FaceList) */ {
 public:
  FaceList();
  virtual ~FaceList();

  FaceList(const FaceList& from);

  inline FaceList& operator=(const FaceList& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FaceList(FaceList&& from) noexcept
    : FaceList() {
    *this = ::std::move(from);
  }

  inline FaceList& operator=(FaceList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const FaceList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FaceList* internal_default_instance() {
    return reinterpret_cast<const FaceList*>(
               &_FaceList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(FaceList* other);
  friend void swap(FaceList& a, FaceList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FaceList* New() const final {
    return CreateMaybeMessage<FaceList>(NULL);
  }

  FaceList* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FaceList>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const FaceList& from);
  void MergeFrom(const FaceList& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FaceList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.my.jni.dlib.data.Face faces = 1;
  int faces_size() const;
  void clear_faces();
  static const int kFacesFieldNumber = 1;
  ::com::my::jni::dlib::data::Face* mutable_faces(int index);
  ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Face >*
      mutable_faces();
  const ::com::my::jni::dlib::data::Face& faces(int index) const;
  ::com::my::jni::dlib::data::Face* add_faces();
  const ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Face >&
      faces() const;

  // @@protoc_insertion_point(class_scope:com.my.jni.dlib.data.FaceList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Face > faces_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_messages_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Landmark

// float x = 1;
inline void Landmark::clear_x() {
  x_ = 0;
}
inline float Landmark::x() const {
  // @@protoc_insertion_point(field_get:com.my.jni.dlib.data.Landmark.x)
  return x_;
}
inline void Landmark::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:com.my.jni.dlib.data.Landmark.x)
}

// float y = 2;
inline void Landmark::clear_y() {
  y_ = 0;
}
inline float Landmark::y() const {
  // @@protoc_insertion_point(field_get:com.my.jni.dlib.data.Landmark.y)
  return y_;
}
inline void Landmark::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:com.my.jni.dlib.data.Landmark.y)
}

// -------------------------------------------------------------------

// LandmarkList

// repeated .com.my.jni.dlib.data.Landmark landmarks = 1;
inline int LandmarkList::landmarks_size() const {
  return landmarks_.size();
}
inline void LandmarkList::clear_landmarks() {
  landmarks_.Clear();
}
inline ::com::my::jni::dlib::data::Landmark* LandmarkList::mutable_landmarks(int index) {
  // @@protoc_insertion_point(field_mutable:com.my.jni.dlib.data.LandmarkList.landmarks)
  return landmarks_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Landmark >*
LandmarkList::mutable_landmarks() {
  // @@protoc_insertion_point(field_mutable_list:com.my.jni.dlib.data.LandmarkList.landmarks)
  return &landmarks_;
}
inline const ::com::my::jni::dlib::data::Landmark& LandmarkList::landmarks(int index) const {
  // @@protoc_insertion_point(field_get:com.my.jni.dlib.data.LandmarkList.landmarks)
  return landmarks_.Get(index);
}
inline ::com::my::jni::dlib::data::Landmark* LandmarkList::add_landmarks() {
  // @@protoc_insertion_point(field_add:com.my.jni.dlib.data.LandmarkList.landmarks)
  return landmarks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Landmark >&
LandmarkList::landmarks() const {
  // @@protoc_insertion_point(field_list:com.my.jni.dlib.data.LandmarkList.landmarks)
  return landmarks_;
}

// -------------------------------------------------------------------

// RectF

// float left = 1;
inline void RectF::clear_left() {
  left_ = 0;
}
inline float RectF::left() const {
  // @@protoc_insertion_point(field_get:com.my.jni.dlib.data.RectF.left)
  return left_;
}
inline void RectF::set_left(float value) {
  
  left_ = value;
  // @@protoc_insertion_point(field_set:com.my.jni.dlib.data.RectF.left)
}

// float top = 2;
inline void RectF::clear_top() {
  top_ = 0;
}
inline float RectF::top() const {
  // @@protoc_insertion_point(field_get:com.my.jni.dlib.data.RectF.top)
  return top_;
}
inline void RectF::set_top(float value) {
  
  top_ = value;
  // @@protoc_insertion_point(field_set:com.my.jni.dlib.data.RectF.top)
}

// float right = 3;
inline void RectF::clear_right() {
  right_ = 0;
}
inline float RectF::right() const {
  // @@protoc_insertion_point(field_get:com.my.jni.dlib.data.RectF.right)
  return right_;
}
inline void RectF::set_right(float value) {
  
  right_ = value;
  // @@protoc_insertion_point(field_set:com.my.jni.dlib.data.RectF.right)
}

// float bottom = 4;
inline void RectF::clear_bottom() {
  bottom_ = 0;
}
inline float RectF::bottom() const {
  // @@protoc_insertion_point(field_get:com.my.jni.dlib.data.RectF.bottom)
  return bottom_;
}
inline void RectF::set_bottom(float value) {
  
  bottom_ = value;
  // @@protoc_insertion_point(field_set:com.my.jni.dlib.data.RectF.bottom)
}

// -------------------------------------------------------------------

// RectFList

// repeated .com.my.jni.dlib.data.RectF rects = 1;
inline int RectFList::rects_size() const {
  return rects_.size();
}
inline void RectFList::clear_rects() {
  rects_.Clear();
}
inline ::com::my::jni::dlib::data::RectF* RectFList::mutable_rects(int index) {
  // @@protoc_insertion_point(field_mutable:com.my.jni.dlib.data.RectFList.rects)
  return rects_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::RectF >*
RectFList::mutable_rects() {
  // @@protoc_insertion_point(field_mutable_list:com.my.jni.dlib.data.RectFList.rects)
  return &rects_;
}
inline const ::com::my::jni::dlib::data::RectF& RectFList::rects(int index) const {
  // @@protoc_insertion_point(field_get:com.my.jni.dlib.data.RectFList.rects)
  return rects_.Get(index);
}
inline ::com::my::jni::dlib::data::RectF* RectFList::add_rects() {
  // @@protoc_insertion_point(field_add:com.my.jni.dlib.data.RectFList.rects)
  return rects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::RectF >&
RectFList::rects() const {
  // @@protoc_insertion_point(field_list:com.my.jni.dlib.data.RectFList.rects)
  return rects_;
}

// -------------------------------------------------------------------

// Face

// .com.my.jni.dlib.data.RectF bound = 1;
inline bool Face::has_bound() const {
  return this != internal_default_instance() && bound_ != NULL;
}
inline void Face::clear_bound() {
  if (GetArenaNoVirtual() == NULL && bound_ != NULL) {
    delete bound_;
  }
  bound_ = NULL;
}
inline const ::com::my::jni::dlib::data::RectF& Face::_internal_bound() const {
  return *bound_;
}
inline const ::com::my::jni::dlib::data::RectF& Face::bound() const {
  const ::com::my::jni::dlib::data::RectF* p = bound_;
  // @@protoc_insertion_point(field_get:com.my.jni.dlib.data.Face.bound)
  return p != NULL ? *p : *reinterpret_cast<const ::com::my::jni::dlib::data::RectF*>(
      &::com::my::jni::dlib::data::_RectF_default_instance_);
}
inline ::com::my::jni::dlib::data::RectF* Face::release_bound() {
  // @@protoc_insertion_point(field_release:com.my.jni.dlib.data.Face.bound)
  
  ::com::my::jni::dlib::data::RectF* temp = bound_;
  bound_ = NULL;
  return temp;
}
inline ::com::my::jni::dlib::data::RectF* Face::mutable_bound() {
  
  if (bound_ == NULL) {
    auto* p = CreateMaybeMessage<::com::my::jni::dlib::data::RectF>(GetArenaNoVirtual());
    bound_ = p;
  }
  // @@protoc_insertion_point(field_mutable:com.my.jni.dlib.data.Face.bound)
  return bound_;
}
inline void Face::set_allocated_bound(::com::my::jni::dlib::data::RectF* bound) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete bound_;
  }
  if (bound) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      bound = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, bound, submessage_arena);
    }
    
  } else {
    
  }
  bound_ = bound;
  // @@protoc_insertion_point(field_set_allocated:com.my.jni.dlib.data.Face.bound)
}

// repeated .com.my.jni.dlib.data.Landmark landmarks = 2;
inline int Face::landmarks_size() const {
  return landmarks_.size();
}
inline void Face::clear_landmarks() {
  landmarks_.Clear();
}
inline ::com::my::jni::dlib::data::Landmark* Face::mutable_landmarks(int index) {
  // @@protoc_insertion_point(field_mutable:com.my.jni.dlib.data.Face.landmarks)
  return landmarks_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Landmark >*
Face::mutable_landmarks() {
  // @@protoc_insertion_point(field_mutable_list:com.my.jni.dlib.data.Face.landmarks)
  return &landmarks_;
}
inline const ::com::my::jni::dlib::data::Landmark& Face::landmarks(int index) const {
  // @@protoc_insertion_point(field_get:com.my.jni.dlib.data.Face.landmarks)
  return landmarks_.Get(index);
}
inline ::com::my::jni::dlib::data::Landmark* Face::add_landmarks() {
  // @@protoc_insertion_point(field_add:com.my.jni.dlib.data.Face.landmarks)
  return landmarks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Landmark >&
Face::landmarks() const {
  // @@protoc_insertion_point(field_list:com.my.jni.dlib.data.Face.landmarks)
  return landmarks_;
}

// -------------------------------------------------------------------

// FaceList

// repeated .com.my.jni.dlib.data.Face faces = 1;
inline int FaceList::faces_size() const {
  return faces_.size();
}
inline void FaceList::clear_faces() {
  faces_.Clear();
}
inline ::com::my::jni::dlib::data::Face* FaceList::mutable_faces(int index) {
  // @@protoc_insertion_point(field_mutable:com.my.jni.dlib.data.FaceList.faces)
  return faces_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Face >*
FaceList::mutable_faces() {
  // @@protoc_insertion_point(field_mutable_list:com.my.jni.dlib.data.FaceList.faces)
  return &faces_;
}
inline const ::com::my::jni::dlib::data::Face& FaceList::faces(int index) const {
  // @@protoc_insertion_point(field_get:com.my.jni.dlib.data.FaceList.faces)
  return faces_.Get(index);
}
inline ::com::my::jni::dlib::data::Face* FaceList::add_faces() {
  // @@protoc_insertion_point(field_add:com.my.jni.dlib.data.FaceList.faces)
  return faces_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::my::jni::dlib::data::Face >&
FaceList::faces() const {
  // @@protoc_insertion_point(field_list:com.my.jni.dlib.data.FaceList.faces)
  return faces_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace dlib
}  // namespace jni
}  // namespace my
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_messages_2eproto
